name: Build Typst Document
run-name: "PDF Build #${{ github.run_number }} by @${{ github.actor }}"

# Trigger: Bei jedem Push auf 'main' (oder 'master')
on:
  push:
    branches:
      - main
  workflow_dispatch: # Erlaubt manuelles Starten via GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Typst CLI Umgebung aufsetzen
      # Dies ist die offizielle Community-Action, die die CLI installiert
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: latest

      # 2b. Nur zu Debug Zwecken: Alle Fonts auflisten, die typst in der Github/Ubuntu Umgebung kennt
      - name: Debug - List Available Fonts
        # Zeigt alle Fonts an, die Typst in dem Ordner findet inkl. interner Namen
        run: typst fonts --font-path ./fonts

      # 3. Kompilieren
      # Passen Sie 'main.typ' an den Namen Ihrer Hauptdatei an
      - name: Compile Document
        run: |
          set -e
          found=false
          
          # Loop über alle .typ Dateien im aktuellen Verzeichnis
          for file in *.typ; do
            # Falls keine Datei existiert, fängt der Loop "*typ" als String -> Check notwendig
            if [ -f "$file" ]; then
              echo "Processing $file ..."
              typst compile --font-path ./fonts "$file"
              found=true
            fi
          done
          
          if [ "$found" = false ]; then
            echo "Error: No .typ files found in root directory."
            exit 1
          fi

      # 4. PDF als Artefakt hochladen
      # Damit steht das PDF nach dem Run zum Download bereit
      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Documents
          path: "*.pdf"
          retention-days: 7